# Generated by Django 2.0.6 on 2018-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immosource',
            name='host',
        ),
        migrations.AddField(
            model_name='immosource',
            name='host_regex',
            field=models.CharField(default='', help_text='The regex of the host who will be used to deduct the `ImmoSource` from the `Search.url`.', max_length=100),
            preserve_default=False,
        ),
    ]
