# Generated by Django 2.0.6 on 2018-06-08 13:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180607_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('original_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('including_charges', models.BooleanField(default=True)),
                ('publication_date', models.DateTimeField()),
                ('type_of_good', models.CharField(blank=True, max_length=100, null=True)),
                ('rooms', models.IntegerField()),
                ('furnished', models.NullBooleanField()),
                ('surface', models.FloatField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), blank=True, null=True, size=None)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Search'),
        ),
    ]
