# Generated by Django 2.0.6 on 2018-06-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180608_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='type_of_good',
            new_name='real_estate_type',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='energy_rate',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='ges',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
