# Generated by Django 2.0.6 on 2018-06-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180608_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Project'),
            preserve_default=False,
        ),
    ]
