# Generated by Django 2.0.6 on 2018-06-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180613_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchresult',
            unique_together={('search', 'original_id')},
        ),
    ]
