# Generated by Django 2.0.6 on 2018-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180614_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='description',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
