# Generated by Django 2.0.6 on 2018-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_searchresult_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
