# Generated by Django 2.0.6 on 2018-06-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_searchresult_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
