# Generated by Django 2.0.6 on 2018-06-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_searchresult_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Feature')),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SearchResult')),
            ],
        ),
        migrations.AddField(
            model_name='searchresult',
            name='features',
            field=models.ManyToManyField(through='api.SearchResultFeature', to='api.Feature'),
        ),
    ]
